﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Painter.Predict
{
    public partial class MLModelLrv
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Red", @"Red"),new InputOutputColumnPair(@"Green", @"Green"),new InputOutputColumnPair(@"Blue", @"Blue")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Red",@"Green",@"Blue"}))      
                                    .Append(mlContext.Regression.Trainers.LightGbm(new LightGbmRegressionTrainer.Options(){NumberOfLeaves=690,NumberOfIterations=31,MinimumExampleCountPerLeaf=20,LearningRate=0.507247039003663,LabelColumnName=@"Lrv",FeatureColumnName=@"Features",ExampleWeightColumnName=null,Booster=new GradientBooster.Options(){SubsampleFraction=1.72614988328877E-05,FeatureFraction=0.99999999,L1Regularization=7.86601288969815E-08,L2Regularization=2.44996765643319E-07},MaximumBinCountPerFeature=110}));

            return pipeline;
        }
    }
}
